# -*- coding: utf-8 -*-
"""Regresión Singapore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kM3S94sF0WayD9knJHKeBG3OJCui7AsV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
from sklearn import linear_model
import sys
from scipy.stats import shapiro
from sklearn.preprocessing import MinMaxScaler, StandardScaler

data = pd.read_csv('DatosSingapore.csv')

data.info()

pd.set_option('display.max_columns', None)
data.head()

X=data.drop('price', axis=1)

y = data['price']

X.columns

X=X.drop('id', axis=1)

X=X.drop('host_id', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7,
                                                                test_size = 0.3, random_state = 42)
lm =linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

y_train_pred = lm.predict(X_train)

print(y_train_pred[0:5])

print('r^2=',lm.score(X_train,y_train))

from sklearn.metrics import r2_score

print(r2_score(y_train, y_train_pred))

stat_price, p_value_price = shapiro(data["price"])
print(f"Columna: price, P-Valor: {p_value_price}")
if p_value_price > 0.05:
    print(f"La columna price parece tener una distribución normal. Se recomienda estandarizar.")
else:
    print(f"La columna price no tiene una distribución normal. Se recomienda normalizar.")

scaler = MinMaxScaler()
data["price"] = scaler.fit_transform(data[["price"]])
data["price"].describe()

residuales = y_train - y_train_pred

resi = pd.DataFrame(X_train)
resi['residuales'] = residuales
resi.head()

fig = plt.figure()
sns.distplot(residuales, bins = 15)
plt.title('Error', fontsize = 15)
plt.xlabel('y_train - y_train_pred', fontsize = 15)
plt.show()

ax1 = sns.distplot(y_train, hist=False, color="r", label="Actual Value")
sns.distplot(y_train_pred, hist=False, color="b", label="Fitted Values" , ax=ax1)

copia = X.copy()
copia['price'] = y

correlation_matrix = copia.corr().round(2)
#heatmap
plt.rcParams['figure.figsize'] = (70, 70)

sns.heatmap(data=correlation_matrix, annot=True)

"""room_type:Entire home/apt = 0.52

accommodates = 0.51

room_type:Private room = -0.5

property_type:Private room in rental unit = -0.48

property_type:Entire serviced apartment = 0.4

minimum_nights = -0.43

minimum_minimum_nights = -0.43

maximum_minimum_nights = -0.43

minimum_nights_avg_ntm = -0.43

number_of_shared_bathrooms = -0.37

calculated_host_listings_count = 0.35

host_total_listings_count = 0.34
"""

X2 = X[['room_type:Entire home/apt','accommodates','room_type:Private room','property_type:Private room in rental unit', 'number_of_shared_bathrooms','minimum_nights_avg_ntm','calculated_host_listings_count']]
y2 = data['price']

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, train_size = 0.7,
                                                                test_size = 0.3, random_state = 42)

lm2 =linear_model.LinearRegression()
model2 = lm2.fit(X2_train,y2_train)

y2_train_pred2= lm2.predict(X2_train)
print(y2_train_pred2[0:5])

lm2.score(X2_train,y2_train)

residuales = y2_train - y2_train_pred2

resi = pd.DataFrame(X2_train)
resi['residuales'] = residuales
resi.head()

fig = plt.figure()
sns.distplot(residuales, bins = 15)
plt.title('Error', fontsize = 15)
plt.xlabel('y2_train - y2_train_pred2', fontsize = 15)
plt.show()

ax1 = sns.distplot(y2_train, hist=False, color="r", label="Actual Value")
sns.distplot(y2_train_pred2, hist=False, color="b", label="Fitted Values" , ax=ax1)

import statsmodels.api as sm

# Convert boolean columns in X2_train to integer type (0 or 1)
X2_train_numeric = X2_train.astype(int)

X2_const_train = sm.add_constant(X2_train_numeric)

modelo_sm = sm.OLS(y2_train, X2_const_train).fit()

print(modelo_sm.summary())

X3 = X[['room_type:Entire home/apt','accommodates','room_type:Private room','property_type:Private room in rental unit',
        'number_of_shared_bathrooms','minimum_nights_avg_ntm','calculated_host_listings_count', 'bedrooms', 'beds']]
y3 = data['price']

X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, train_size = 0.7,
                                                                test_size = 0.3, random_state = 42)

lm3 =linear_model.LinearRegression()
model3 = lm3.fit(X3_train,y3_train)

y3_train_pred3= lm3.predict(X3_train)
print(y3_train_pred3[0:5])

lm3.score(X3_train,y3_train)

residuales = y3_train - y3_train_pred3

resi = pd.DataFrame(X3_train)
resi['residuales'] = residuales
resi.head()

fig = plt.figure()
sns.distplot(residuales, bins = 15)
plt.title('Error', fontsize = 15)
plt.xlabel('y3_train - y3_train_pred3', fontsize = 15)
plt.show()

ax1 = sns.distplot(y3_train, hist=False, color="r", label="Actual Value")
sns.distplot(y3_train_pred3, hist=False, color="b", label="Fitted Values" , ax=ax1)

X3_train_numeric = X3_train.astype(int)

X3_const_train = sm.add_constant(X3_train_numeric)

modelo_sm = sm.OLS(y3_train, X3_const_train).fit()

print(modelo_sm.summary())

X4 = X[['room_type:Entire home/apt','accommodates','room_type:Private room','property_type:Private room in rental unit']]
y4 = data['price']

X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, train_size = 0.7,
                                                                test_size = 0.3, random_state = 42)

lm4 =linear_model.LinearRegression()
model4 = lm4.fit(X4_train,y4_train)

y4_train_pred4= lm4.predict(X4_train)
print(y4_train_pred4[0:5])

lm4.score(X4_train,y4_train)

residuales = y4_train - y4_train_pred4

resi = pd.DataFrame(X4_train)
resi['residuales'] = residuales
resi.head()

fig = plt.figure()
sns.distplot(residuales, bins = 15)
plt.title('Error', fontsize = 15)
plt.xlabel('y4_train - y4_train_pred4', fontsize = 15)
plt.show()

ax1 = sns.distplot(y4_train, hist=False, color="r", label="Actual Value")
sns.distplot(y4_train_pred4, hist=False, color="b", label="Fitted Values" , ax=ax1)

# Convert boolean columns in X4_train to integer type (0 or 1)
X4_train_numeric = X4_train.astype(int)

X4_const_train = sm.add_constant(X4_train_numeric)

modelo_sm = sm.OLS(y4_train, X4_const_train).fit()

print(modelo_sm.summary())