# -*- coding: utf-8 -*-
"""Modelo clasificación

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8XprdybPvsez2wkiNhjaUVXmqLf85T-
"""

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import plotly.express as px
import sys
from sklearn.feature_selection import RFE
from sklearn import preprocessing

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv('DatosSingapore.csv')

data.info()

pd.set_option('display.max_columns', None)
data.head()

cols = ["review_scores_rating", "price", "amenities_number"]

scaler = StandardScaler()
scaled = scaler.fit_transform(data[cols])

data["simple_score"] = (
    scaled[:,0]        # rating
    - scaled[:,1]      # precio invertido
    + scaled[:,2]      # amenities
)

threshold = data["simple_score"].median()
data["recommended"] = (data["simple_score"] >= threshold).astype(int)

print("Proportions:")
print(data["recommended"].value_counts(normalize=True))

data[["review_scores_rating","price","amenities_number","simple_score","recommended"]].head()

features = ["price","accommodates","bedrooms","bathrooms","amenities_number","review_scores_rating"]

X = data[features]
y = data['recommended']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.80, test_size = 0.20 ,
                                                   random_state = 42, stratify = y)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression()

model.fit(X_train_scaled, y_train)

np.set_printoptions(threshold=sys.maxsize)
model.predict_proba(X_train_scaled)

model.score(X_train_scaled, y_train)

model.coef_

y_train_predi = model.predict(X_train_scaled)

print(classification_report(y_train, y_train_predi))

cf = confusion_matrix(y_train, y_train_predi)
print(cf)

y_pred_test = model.predict(X_test_scaled)

print(classification_report(y_test, y_pred_test))

cft = confusion_matrix(y_test, y_pred_test)
print(cft)