# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhuoga8X8Hhbxnh5agE_D3zqrcUm-jbr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
from sklearn import linear_model
import sys
from scipy.stats import shapiro
from sklearn.preprocessing import MinMaxScaler, StandardScaler

data = pd.read_csv('DatosSingapore.csv')

data.info()

pd.set_option('display.max_columns', None)
data.head()

X=data.drop('price', axis=1)

y = data['price']

X.columns

X=X.drop('id', axis=1)

X=X.drop('host_id', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7,
                                                                test_size = 0.3, random_state = 42)
lm =linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

y_train_pred = lm.predict(X_train)

print(y_train_pred[0:5])

print('r^2=',lm.score(X_train,y_train))

stat_price, p_value_price = shapiro(data["price"])
print(f"Columna: price, P-Valor: {p_value_price}")
if p_value_price > 0.05:
    print(f"La columna price parece tener una distribución normal. Se recomienda estandarizar.")
else:
    print(f"La columna price no tiene una distribución normal. Se recomienda normalizar.")

scaler = MinMaxScaler()
data["price"] = scaler.fit_transform(data[["price"]])
data["price"].describe()

residuales = y_train - y_train_pred

resi = pd.DataFrame(X_train)
resi['residuales'] = residuales
resi.head()

fig = plt.figure()
sns.distplot(residuales, bins = 15)
plt.title('Error', fontsize = 15)
plt.xlabel('y_train - y_train_pred', fontsize = 15)
plt.show()

ax1 = sns.distplot(y_train, hist=False, color="r", label="Actual Value")
sns.distplot(y_train_pred, hist=False, color="b", label="Fitted Values" , ax=ax1)